### ISSUE TITLE
Use final vowel to designate predicate place

### ISSUE THREAD

**Issue by trans** [LogosInitiative/logla#6]
Since the last vowel of a "brivla" is effectively useless in distinguishing one word from another, it could be used to specify the predicate place intended, instead of using `se`, `te`, `ve` or `xe` (Lojban cmavo).

```
klama     =>  klama
se klama  =>  klame
te klama  =>  klami
ve klama  =>  klamo
xe klama  =>  klamu
```

It just seems a very natural extension of the predicate nature of words.

**Comment by thetommoore** [comment]
This is a rather large change in morphology to accommodate a specific case, but maybe it would work better in conjunction with significant grammatical changes, such as marking words with these brivla to indicate their role in the sentence.

**Comment by whitten** [comment]
Wouldn't the removal of the cmavo mean that the language is less regular?
I'm just starting, so I'm not sure what a "brivia" is, but this seems to be moving Logla to an "agglutinative-sometimes" language.  Any feature used only sometimes increases the cognitive load on the learner.

**Comment by trans** [comment]
Btw, It remains to be seen how the morphology actually turns. So this may not even be applicable. We can tentatively assume it will remains essentially like Loglan/Lojban, but it still a discussion we will have to have (on the [mailing list](https://groups.google.com/forum/#!forum/logla)) and I imagine it will be one of the longer ones.

**Comment by trans** [comment]
@mellow-mellow I've considered the case of using the vowel to indicate the role in the selbri (lojban verb), which is very similar to Latin and many other languages. The nice thing about that approach is sumti (lojban object) order becomes completely free. However, there are some complications, such as tanru (lojban adjective) --would they have to have a matching vowel? And we would still need special particles to refer to the inner positions of the sumti, which is the source of a fair bit of verbosity. And what about relative clauses? Would we have to "decline" ke'a too? And so on. I admit some of this is attractive to me (not the least of which is how much people love the sound of Italian b/c of those matching end-vowels), but this would be a much more substantial change to the language then what I am proposing. 

Also there is one additional thing working against that idea. Most modern languages have evolved away from such systems in favor of word order. Arabic is a good case in point --it is actually in the middle of just such an evolution right now.

All that is not to say it might not be the better approach. Perhaps it is. But it would take quite a bit of analysis to consider all the implications to figure out if it would really provide a marked improvement. (My guess is that the improvements would prove marginal at best --well, other than that sexy Italian-style :wink:)

**Comment by trans** [comment]
@whitten It would be "agglutinative" in this one respect. I wouldn't want the language to move any further in an agglutinative direction, but in this one case it seems a clear advantage. Btw, Lojban does have a few cases of this already (more or less), e.g. broda, brode, brodi, brodo, brodu.

**Comment by thetommoore** [comment]
@trans I was thinking more along the lines of turning selbri into particles, like pre- or postpositions, like in Japanese. It would require a thorough reworking of the language, though, so I don't necessarily endorse it.

**Comment by trans** [comment]
@mellow-mellow Do you mean _case tags_? Loglan actually has these, but I think they are considered experimental. It's not really that far out of the question. Modern programming languages now have named arguments. A modern predicate-based language could, analogously, have the same thing.

**Comment by thetommoore** [comment]
@trans Sounds like cause to open another thread then! I'm not personally familiar with them in Lojban.

**Comment by whitten** [comment]
In English, I think a lot of the case tag information is carried by prepositions.
For example, the gift was given "by" John, "to" Mary, "for" Christmas, "when" she woke up.  Is there any reason to build case tags into the words themselves? It seems the preposition words give a lot of orthagonality to English. Especially if you want to have Davidsonian Event structures.

**Comment by trans** [comment]
@whitten I may misunderstand your point, but if I do understand then this is what I was trying to explain in my long post to @mellow-mellow. I am not proposing that case tags be in the words themselves. All I am proposing is the the places of the predicate, when used as a argument, be accessible that way. For example, the Loglan word 'ditca' means "x1 teaches x2 to x3". But lets say I wanted to say "the student taught the teacher". In Loglan that would be something like*:

```
le fu ditca pa ditca le ditca 
```

The word 'fu' _converts_ the word 'ditca' so that the third argument (x3) becomes the first, and thus what we are referencing. In my proposal this would instead be something like:

```
le ditci pa ditca le ditca 
```

So we haven't used any case tags to designate the relation of the objects to the verb ('pa ditca'), we are still just using word order here. But the use of the ending 'i' in 'ditci' allowed us to get rid of 'fu' and still reference the meaning of the third argument.

(*Note, technically I am not sure if `fu ditca` means student in Loglan, it would if this were in Lojban, but in Loglan it might just mean "the teachable one". But close enough.)

**Comment by trans** [comment]
Interesting [paper](http://semanticsarchive.net/Archive/jFhNWM2M/eventbasedsemantics.pdf) explaining Davidsonian Events.

**Comment by thetommoore** [comment]
It would seem that the word for teach is `ctuca`, with a second place for student/audience, so a student might be called `le fe ctuca`. Also, I didn't know you were talking about the `fV` place markers; those aren't _quite_ case tags, since the LLG and friends didn't really keep to a specific semantic system for place order.

I finally got around to reading that paper, having been open in my tabs for over a month, and that might be an interesting new direction grammatically if we were to work those sorts of predicates into the language. Perhaps they would work like prepositions?

**Comment by trans** [comment]
I've decided to reject this proposal. After a few days of deep analysis on how to simplify the morphology of Loglan/Lojban while still incorporating this idea a whole new infinitely better approach came to light. I will explain is soon in a new proposal, suffice to say in covers what this proposal could do and takes it to a whole new level. As it turns out  @mellow-mellow , it very much does have to do with case-tags.
